# Stage 1: Build the React application
FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY client/package*.json ./
RUN npm install

COPY client/ ./

RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
